/* tslint:disable */
/* eslint-disable */
/**
 * Individual Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'individualId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'content'?: string;
}
/**
 * 
 * @export
 * @interface AddressInput
 */
export interface AddressInput {
    /**
     * 
     * @type {string}
     * @memberof AddressInput
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressInput
     */
    'individualId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressInput
     */
    'street'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressInput
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressInput
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressInput
     */
    'zipCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressInput
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressInput
     */
    'addressee'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressInput
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressInput
     */
    'email'?: string;
    /**
     * 
     * @type {{ [key: string]: Tag; }}
     * @memberof AddressInput
     */
    'tags'?: { [key: string]: Tag; };
}
/**
 * 
 * @export
 * @interface AddressOutput
 */
export interface AddressOutput {
    /**
     * 
     * @type {string}
     * @memberof AddressOutput
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressOutput
     */
    'individualId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressOutput
     */
    'street'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressOutput
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressOutput
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressOutput
     */
    'zipCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressOutput
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressOutput
     */
    'addressee'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressOutput
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressOutput
     */
    'email'?: string;
}
/**
 * 
 * @export
 * @interface Individual
 */
export interface Individual {
    /**
     * 
     * @type {string}
     * @memberof Individual
     */
    'id'?: string;
    /**
     * 
     * @type {Array<Address>}
     * @memberof Individual
     */
    'addresses'?: Array<Address>;
    /**
     * 
     * @type {Array<IndividualPrivateserviceprovidersInner>}
     * @memberof Individual
     */
    'privateserviceproviders'?: Array<IndividualPrivateserviceprovidersInner>;
    /**
     * 
     * @type {{ [key: string]: Tag; }}
     * @memberof Individual
     */
    'tags'?: { [key: string]: Tag; };
}
/**
 * 
 * @export
 * @interface IndividualInput
 */
export interface IndividualInput {
    /**
     * 
     * @type {Array<AddressInput>}
     * @memberof IndividualInput
     */
    'newaddresses'?: Array<AddressInput>;
    /**
     * 
     * @type {Array<string>}
     * @memberof IndividualInput
     */
    'newprivateserviceproviders'?: Array<string>;
}
/**
 * 
 * @export
 * @interface IndividualPrivateserviceprovidersInner
 */
export interface IndividualPrivateserviceprovidersInner {
    /**
     * 
     * @type {string}
     * @memberof IndividualPrivateserviceprovidersInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IndividualPrivateserviceprovidersInner
     */
    'individualid'?: string;
    /**
     * 
     * @type {{ [key: string]: Tag; }}
     * @memberof IndividualPrivateserviceprovidersInner
     */
    'tags'?: { [key: string]: Tag; };
}
/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * The name of the tag
     * @type {string}
     * @memberof Tag
     */
    'Name'?: string;
    /**
     * 
     * @type {TagValue}
     * @memberof Tag
     */
    'Value'?: TagValue;
    /**
     * Whether the tag is private
     * @type {boolean}
     * @memberof Tag
     */
    'Private'?: boolean;
    /**
     * Whether the tag is required
     * @type {boolean}
     * @memberof Tag
     */
    'Required'?: boolean;
    /**
     * Whether the tag is editable
     * @type {boolean}
     * @memberof Tag
     */
    'Editable'?: boolean;
}
/**
 * @type TagValue
 * The value of the tag
 * @export
 */
export type TagValue = boolean | number | string;

/**
 * 
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * Unique identifier for the user
     * @type {string}
     * @memberof UserInfo
     */
    'UserID'?: string;
    /**
     * Unique identifier for the individual
     * @type {string}
     * @memberof UserInfo
     */
    'IndividualID'?: string;
    /**
     * ownertoken
     * @type {string}
     * @memberof UserInfo
     */
    'Ownertoken'?: string;
    /**
     * Jwtoken for authentication
     * @type {string}
     * @memberof UserInfo
     */
    'Jwtoken'?: string;
    /**
     * GMail Auth token if authorized
     * @type {string}
     * @memberof UserInfo
     */
    'Gmailaccesstoken'?: string;
    /**
     * valid authorization till
     * @type {number}
     * @memberof UserInfo
     */
    'ValidTill'?: number;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new individual
         * @param {IndividualInput} individualInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createIndividual: async (individualInput: IndividualInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'individualInput' is not null or undefined
            assertParamExists('createIndividual', 'individualInput', individualInput)
            const localVarPath = `/individuals`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(individualInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a specific address for an individual by ID and address ID
         * @param {string} addressId ID of the address
         * @param {string} beneficiaryToken Beneficiary token for authorization
         * @param {string} beneficiaryId Beneficiary id for authorization
         * @param {string} [individualId] individualId id for authorization in case of owner token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAddress: async (addressId: string, beneficiaryToken: string, beneficiaryId: string, individualId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addressId' is not null or undefined
            assertParamExists('deleteAddress', 'addressId', addressId)
            // verify required parameter 'beneficiaryToken' is not null or undefined
            assertParamExists('deleteAddress', 'beneficiaryToken', beneficiaryToken)
            // verify required parameter 'beneficiaryId' is not null or undefined
            assertParamExists('deleteAddress', 'beneficiaryId', beneficiaryId)
            const localVarPath = `/addresses/{addressId}`
                .replace(`{${"addressId"}}`, encodeURIComponent(String(addressId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (beneficiaryToken !== undefined) {
                localVarQueryParameter['beneficiary_token'] = beneficiaryToken;
            }

            if (beneficiaryId !== undefined) {
                localVarQueryParameter['beneficiaryId'] = beneficiaryId;
            }

            if (individualId !== undefined) {
                localVarQueryParameter['individualId'] = individualId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete an individual by ID
         * @param {string} id ID of the individual
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteIndividual: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteIndividual', 'id', id)
            const localVarPath = `/individuals/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a specific address for an individual by ID and address ID
         * @param {string} addressId ID of the address
         * @param {string} beneficiaryToken Beneficiary token for authorization
         * @param {string} beneficiaryId Beneficiary id for authorization
         * @param {string} [individualId] individualId id for authorization in case of owner token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAddress: async (addressId: string, beneficiaryToken: string, beneficiaryId: string, individualId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addressId' is not null or undefined
            assertParamExists('getAddress', 'addressId', addressId)
            // verify required parameter 'beneficiaryToken' is not null or undefined
            assertParamExists('getAddress', 'beneficiaryToken', beneficiaryToken)
            // verify required parameter 'beneficiaryId' is not null or undefined
            assertParamExists('getAddress', 'beneficiaryId', beneficiaryId)
            const localVarPath = `/addresses/{addressId}`
                .replace(`{${"addressId"}}`, encodeURIComponent(String(addressId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (beneficiaryToken !== undefined) {
                localVarQueryParameter['beneficiary_token'] = beneficiaryToken;
            }

            if (beneficiaryId !== undefined) {
                localVarQueryParameter['beneficiaryId'] = beneficiaryId;
            }

            if (individualId !== undefined) {
                localVarQueryParameter['individualId'] = individualId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get an individual by ID
         * @param {string} id ID of the individual
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIndividualDetails: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getIndividualDetails', 'id', id)
            const localVarPath = `/individuals/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a list of all individuals
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIndividuals: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/individuals`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves userinfo in JSON format
         * @summary Retrieve Userinfo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/userinfo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an existing address for an individual by ID and address ID
         * @param {string} addressId ID of the address
         * @param {string} beneficiaryToken Beneficiary token for authorization
         * @param {string} beneficiaryId Beneficiary id for authorization
         * @param {AddressInput} addressInput Address data to be updated
         * @param {string} [individualId] individualId id for authorization in case of owner token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAddress: async (addressId: string, beneficiaryToken: string, beneficiaryId: string, addressInput: AddressInput, individualId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addressId' is not null or undefined
            assertParamExists('updateAddress', 'addressId', addressId)
            // verify required parameter 'beneficiaryToken' is not null or undefined
            assertParamExists('updateAddress', 'beneficiaryToken', beneficiaryToken)
            // verify required parameter 'beneficiaryId' is not null or undefined
            assertParamExists('updateAddress', 'beneficiaryId', beneficiaryId)
            // verify required parameter 'addressInput' is not null or undefined
            assertParamExists('updateAddress', 'addressInput', addressInput)
            const localVarPath = `/addresses/{addressId}`
                .replace(`{${"addressId"}}`, encodeURIComponent(String(addressId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (beneficiaryToken !== undefined) {
                localVarQueryParameter['beneficiary_token'] = beneficiaryToken;
            }

            if (beneficiaryId !== undefined) {
                localVarQueryParameter['beneficiaryId'] = beneficiaryId;
            }

            if (individualId !== undefined) {
                localVarQueryParameter['individualId'] = individualId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addressInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an individual by ID
         * @param {string} id ID of the individual
         * @param {IndividualInput} individualInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateIndividual: async (id: string, individualInput: IndividualInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateIndividual', 'id', id)
            // verify required parameter 'individualInput' is not null or undefined
            assertParamExists('updateIndividual', 'individualInput', individualInput)
            const localVarPath = `/individuals/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(individualInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new individual
         * @param {IndividualInput} individualInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createIndividual(individualInput: IndividualInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createIndividual(individualInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createIndividual']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a specific address for an individual by ID and address ID
         * @param {string} addressId ID of the address
         * @param {string} beneficiaryToken Beneficiary token for authorization
         * @param {string} beneficiaryId Beneficiary id for authorization
         * @param {string} [individualId] individualId id for authorization in case of owner token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAddress(addressId: string, beneficiaryToken: string, beneficiaryId: string, individualId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAddress(addressId, beneficiaryToken, beneficiaryId, individualId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteAddress']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete an individual by ID
         * @param {string} id ID of the individual
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteIndividual(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteIndividual(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteIndividual']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a specific address for an individual by ID and address ID
         * @param {string} addressId ID of the address
         * @param {string} beneficiaryToken Beneficiary token for authorization
         * @param {string} beneficiaryId Beneficiary id for authorization
         * @param {string} [individualId] individualId id for authorization in case of owner token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAddress(addressId: string, beneficiaryToken: string, beneficiaryId: string, individualId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AddressOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAddress(addressId, beneficiaryToken, beneficiaryId, individualId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAddress']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get an individual by ID
         * @param {string} id ID of the individual
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIndividualDetails(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Individual>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getIndividualDetails(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getIndividualDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a list of all individuals
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIndividuals(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getIndividuals(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getIndividuals']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves userinfo in JSON format
         * @summary Retrieve Userinfo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserInfo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserInfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserInfo(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getUserInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an existing address for an individual by ID and address ID
         * @param {string} addressId ID of the address
         * @param {string} beneficiaryToken Beneficiary token for authorization
         * @param {string} beneficiaryId Beneficiary id for authorization
         * @param {AddressInput} addressInput Address data to be updated
         * @param {string} [individualId] individualId id for authorization in case of owner token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAddress(addressId: string, beneficiaryToken: string, beneficiaryId: string, addressInput: AddressInput, individualId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAddress(addressId, beneficiaryToken, beneficiaryId, addressInput, individualId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateAddress']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an individual by ID
         * @param {string} id ID of the individual
         * @param {IndividualInput} individualInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateIndividual(id: string, individualInput: IndividualInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateIndividual(id, individualInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateIndividual']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new individual
         * @param {IndividualInput} individualInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createIndividual(individualInput: IndividualInput, options?: any): AxiosPromise<void> {
            return localVarFp.createIndividual(individualInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a specific address for an individual by ID and address ID
         * @param {string} addressId ID of the address
         * @param {string} beneficiaryToken Beneficiary token for authorization
         * @param {string} beneficiaryId Beneficiary id for authorization
         * @param {string} [individualId] individualId id for authorization in case of owner token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAddress(addressId: string, beneficiaryToken: string, beneficiaryId: string, individualId?: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteAddress(addressId, beneficiaryToken, beneficiaryId, individualId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete an individual by ID
         * @param {string} id ID of the individual
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteIndividual(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteIndividual(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a specific address for an individual by ID and address ID
         * @param {string} addressId ID of the address
         * @param {string} beneficiaryToken Beneficiary token for authorization
         * @param {string} beneficiaryId Beneficiary id for authorization
         * @param {string} [individualId] individualId id for authorization in case of owner token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAddress(addressId: string, beneficiaryToken: string, beneficiaryId: string, individualId?: string, options?: any): AxiosPromise<AddressOutput> {
            return localVarFp.getAddress(addressId, beneficiaryToken, beneficiaryId, individualId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get an individual by ID
         * @param {string} id ID of the individual
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIndividualDetails(id: string, options?: any): AxiosPromise<Individual> {
            return localVarFp.getIndividualDetails(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a list of all individuals
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIndividuals(options?: any): AxiosPromise<Array<string>> {
            return localVarFp.getIndividuals(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves userinfo in JSON format
         * @summary Retrieve Userinfo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfo(options?: any): AxiosPromise<UserInfo> {
            return localVarFp.getUserInfo(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an existing address for an individual by ID and address ID
         * @param {string} addressId ID of the address
         * @param {string} beneficiaryToken Beneficiary token for authorization
         * @param {string} beneficiaryId Beneficiary id for authorization
         * @param {AddressInput} addressInput Address data to be updated
         * @param {string} [individualId] individualId id for authorization in case of owner token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAddress(addressId: string, beneficiaryToken: string, beneficiaryId: string, addressInput: AddressInput, individualId?: string, options?: any): AxiosPromise<void> {
            return localVarFp.updateAddress(addressId, beneficiaryToken, beneficiaryId, addressInput, individualId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an individual by ID
         * @param {string} id ID of the individual
         * @param {IndividualInput} individualInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateIndividual(id: string, individualInput: IndividualInput, options?: any): AxiosPromise<void> {
            return localVarFp.updateIndividual(id, individualInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Create a new individual
     * @param {IndividualInput} individualInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createIndividual(individualInput: IndividualInput, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createIndividual(individualInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a specific address for an individual by ID and address ID
     * @param {string} addressId ID of the address
     * @param {string} beneficiaryToken Beneficiary token for authorization
     * @param {string} beneficiaryId Beneficiary id for authorization
     * @param {string} [individualId] individualId id for authorization in case of owner token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteAddress(addressId: string, beneficiaryToken: string, beneficiaryId: string, individualId?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteAddress(addressId, beneficiaryToken, beneficiaryId, individualId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete an individual by ID
     * @param {string} id ID of the individual
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteIndividual(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteIndividual(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a specific address for an individual by ID and address ID
     * @param {string} addressId ID of the address
     * @param {string} beneficiaryToken Beneficiary token for authorization
     * @param {string} beneficiaryId Beneficiary id for authorization
     * @param {string} [individualId] individualId id for authorization in case of owner token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAddress(addressId: string, beneficiaryToken: string, beneficiaryId: string, individualId?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAddress(addressId, beneficiaryToken, beneficiaryId, individualId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get an individual by ID
     * @param {string} id ID of the individual
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getIndividualDetails(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getIndividualDetails(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a list of all individuals
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getIndividuals(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getIndividuals(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves userinfo in JSON format
     * @summary Retrieve Userinfo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getUserInfo(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getUserInfo(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an existing address for an individual by ID and address ID
     * @param {string} addressId ID of the address
     * @param {string} beneficiaryToken Beneficiary token for authorization
     * @param {string} beneficiaryId Beneficiary id for authorization
     * @param {AddressInput} addressInput Address data to be updated
     * @param {string} [individualId] individualId id for authorization in case of owner token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateAddress(addressId: string, beneficiaryToken: string, beneficiaryId: string, addressInput: AddressInput, individualId?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateAddress(addressId, beneficiaryToken, beneficiaryId, addressInput, individualId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an individual by ID
     * @param {string} id ID of the individual
     * @param {IndividualInput} individualInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateIndividual(id: string, individualInput: IndividualInput, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateIndividual(id, individualInput, options).then((request) => request(this.axios, this.basePath));
    }
}



