/* tslint:disable */
/* eslint-disable */
/**
 * JustWhere.io API
 * API for retrieving valid UserIDs on the JustWhere.io platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface GetValidUsers200Response
 */
export interface GetValidUsers200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetValidUsers200Response
     */
    'validUserIds'?: Array<string>;
}
/**
 * 
 * @export
 * @interface GetValidUsers400Response
 */
export interface GetValidUsers400Response {
    /**
     * 
     * @type {string}
     * @memberof GetValidUsers400Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface GetValidUsers500Response
 */
export interface GetValidUsers500Response {
    /**
     * 
     * @type {string}
     * @memberof GetValidUsers500Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface GetValidUsersRequest
 */
export interface GetValidUsersRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetValidUsersRequest
     */
    'userIds'?: Array<string>;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve a list of valid UserIDs on the JustWhere.io platform from a provided list of UserIDs.
         * @summary Get list of valid UserIDs
         * @param {GetValidUsersRequest} getValidUsersRequest A JSON object containing a list of UserIDs to be validated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getValidUsers: async (getValidUsersRequest: GetValidUsersRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'getValidUsersRequest' is not null or undefined
            assertParamExists('getValidUsers', 'getValidUsersRequest', getValidUsersRequest)
            const localVarPath = `/contacts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getValidUsersRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve a list of valid UserIDs on the JustWhere.io platform from a provided list of UserIDs.
         * @summary Get list of valid UserIDs
         * @param {GetValidUsersRequest} getValidUsersRequest A JSON object containing a list of UserIDs to be validated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getValidUsers(getValidUsersRequest: GetValidUsersRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetValidUsers200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getValidUsers(getValidUsersRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getValidUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Retrieve a list of valid UserIDs on the JustWhere.io platform from a provided list of UserIDs.
         * @summary Get list of valid UserIDs
         * @param {GetValidUsersRequest} getValidUsersRequest A JSON object containing a list of UserIDs to be validated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getValidUsers(getValidUsersRequest: GetValidUsersRequest, options?: any): AxiosPromise<GetValidUsers200Response> {
            return localVarFp.getValidUsers(getValidUsersRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Retrieve a list of valid UserIDs on the JustWhere.io platform from a provided list of UserIDs.
     * @summary Get list of valid UserIDs
     * @param {GetValidUsersRequest} getValidUsersRequest A JSON object containing a list of UserIDs to be validated
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getValidUsers(getValidUsersRequest: GetValidUsersRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getValidUsers(getValidUsersRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



