/* tslint:disable */
/* eslint-disable */
/**
 * Notification Service API
 * API for managing notifications for various entities
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface MessageBody
 */
export interface MessageBody {
    /**
     * Unique identifier for the message body
     * @type {string}
     * @memberof MessageBody
     */
    'id'?: string;
    /**
     * External identifier
     * @type {string}
     * @memberof MessageBody
     */
    'ExternalID'?: string;
    /**
     * JSON text for the message
     * @type {object}
     * @memberof MessageBody
     */
    'Message'?: object;
    /**
     * 
     * @type {Status}
     * @memberof MessageBody
     */
    'Status'?: Status;
    /**
     * 
     * @type {number}
     * @memberof MessageBody
     */
    'Created'?: number;
    /**
     * 
     * @type {number}
     * @memberof MessageBody
     */
    'Updated'?: number;
}


/**
 * Status of the message
 * @export
 * @enum {string}
 */

export const Status = {
    New: 'new',
    Processed: 'processed'
} as const;

export type Status = typeof Status[keyof typeof Status];



/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete notification details for a specific entity
         * @param {DeleteNotificationEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
         * @param {string} id The ID of the notification itself
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteNotification: async (entitytype: DeleteNotificationEntitytypeEnum, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'entitytype' is not null or undefined
            assertParamExists('deleteNotification', 'entitytype', entitytype)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteNotification', 'id', id)
            const localVarPath = `/notification/{entitytype}/{id}`
                .replace(`{${"entitytype"}}`, encodeURIComponent(String(entitytype)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all notification details for a specific entity
         * @param {GetAllNotificationsEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
         * @param {string} id The ID of the entity
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllNotifications: async (entitytype: GetAllNotificationsEntitytypeEnum, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'entitytype' is not null or undefined
            assertParamExists('getAllNotifications', 'entitytype', entitytype)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getAllNotifications', 'id', id)
            const localVarPath = `/notifications/{entitytype}/{id}`
                .replace(`{${"entitytype"}}`, encodeURIComponent(String(entitytype)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get notification details for a specific entity
         * @param {GetNotificationDetailsEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
         * @param {string} id The ID of the notification itself
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNotificationDetails: async (entitytype: GetNotificationDetailsEntitytypeEnum, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'entitytype' is not null or undefined
            assertParamExists('getNotificationDetails', 'entitytype', entitytype)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getNotificationDetails', 'id', id)
            const localVarPath = `/notification/{entitytype}/{id}`
                .replace(`{${"entitytype"}}`, encodeURIComponent(String(entitytype)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update notification details for a specific entity
         * @param {UpdateNotificationEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
         * @param {string} id The ID of the notification itself
         * @param {MessageBody} messageBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateNotification: async (entitytype: UpdateNotificationEntitytypeEnum, id: string, messageBody: MessageBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'entitytype' is not null or undefined
            assertParamExists('updateNotification', 'entitytype', entitytype)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateNotification', 'id', id)
            // verify required parameter 'messageBody' is not null or undefined
            assertParamExists('updateNotification', 'messageBody', messageBody)
            const localVarPath = `/notification/{entitytype}/{id}`
                .replace(`{${"entitytype"}}`, encodeURIComponent(String(entitytype)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(messageBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Delete notification details for a specific entity
         * @param {DeleteNotificationEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
         * @param {string} id The ID of the notification itself
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteNotification(entitytype: DeleteNotificationEntitytypeEnum, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteNotification(entitytype, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteNotification']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all notification details for a specific entity
         * @param {GetAllNotificationsEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
         * @param {string} id The ID of the entity
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllNotifications(entitytype: GetAllNotificationsEntitytypeEnum, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MessageBody>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllNotifications(entitytype, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAllNotifications']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get notification details for a specific entity
         * @param {GetNotificationDetailsEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
         * @param {string} id The ID of the notification itself
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNotificationDetails(entitytype: GetNotificationDetailsEntitytypeEnum, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNotificationDetails(entitytype, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getNotificationDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update notification details for a specific entity
         * @param {UpdateNotificationEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
         * @param {string} id The ID of the notification itself
         * @param {MessageBody} messageBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateNotification(entitytype: UpdateNotificationEntitytypeEnum, id: string, messageBody: MessageBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateNotification(entitytype, id, messageBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateNotification']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Delete notification details for a specific entity
         * @param {DeleteNotificationEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
         * @param {string} id The ID of the notification itself
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteNotification(entitytype: DeleteNotificationEntitytypeEnum, id: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteNotification(entitytype, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all notification details for a specific entity
         * @param {GetAllNotificationsEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
         * @param {string} id The ID of the entity
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllNotifications(entitytype: GetAllNotificationsEntitytypeEnum, id: string, options?: any): AxiosPromise<Array<MessageBody>> {
            return localVarFp.getAllNotifications(entitytype, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get notification details for a specific entity
         * @param {GetNotificationDetailsEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
         * @param {string} id The ID of the notification itself
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNotificationDetails(entitytype: GetNotificationDetailsEntitytypeEnum, id: string, options?: any): AxiosPromise<MessageBody> {
            return localVarFp.getNotificationDetails(entitytype, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update notification details for a specific entity
         * @param {UpdateNotificationEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
         * @param {string} id The ID of the notification itself
         * @param {MessageBody} messageBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateNotification(entitytype: UpdateNotificationEntitytypeEnum, id: string, messageBody: MessageBody, options?: any): AxiosPromise<MessageBody> {
            return localVarFp.updateNotification(entitytype, id, messageBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Delete notification details for a specific entity
     * @param {DeleteNotificationEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
     * @param {string} id The ID of the notification itself
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteNotification(entitytype: DeleteNotificationEntitytypeEnum, id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteNotification(entitytype, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all notification details for a specific entity
     * @param {GetAllNotificationsEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
     * @param {string} id The ID of the entity
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAllNotifications(entitytype: GetAllNotificationsEntitytypeEnum, id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAllNotifications(entitytype, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get notification details for a specific entity
     * @param {GetNotificationDetailsEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
     * @param {string} id The ID of the notification itself
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getNotificationDetails(entitytype: GetNotificationDetailsEntitytypeEnum, id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getNotificationDetails(entitytype, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update notification details for a specific entity
     * @param {UpdateNotificationEntitytypeEnum} entitytype The type of entity (account, user, individual, serviceprovider, beneficiary)
     * @param {string} id The ID of the notification itself
     * @param {MessageBody} messageBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateNotification(entitytype: UpdateNotificationEntitytypeEnum, id: string, messageBody: MessageBody, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateNotification(entitytype, id, messageBody, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const DeleteNotificationEntitytypeEnum = {
    Account: 'account',
    User: 'user',
    Individual: 'individual',
    Serviceprovider: 'serviceprovider',
    Beneficiary: 'beneficiary'
} as const;
export type DeleteNotificationEntitytypeEnum = typeof DeleteNotificationEntitytypeEnum[keyof typeof DeleteNotificationEntitytypeEnum];
/**
 * @export
 */
export const GetAllNotificationsEntitytypeEnum = {
    Account: 'account',
    User: 'user',
    Individual: 'individual',
    Serviceprovider: 'serviceprovider',
    Beneficiary: 'beneficiary'
} as const;
export type GetAllNotificationsEntitytypeEnum = typeof GetAllNotificationsEntitytypeEnum[keyof typeof GetAllNotificationsEntitytypeEnum];
/**
 * @export
 */
export const GetNotificationDetailsEntitytypeEnum = {
    Account: 'account',
    User: 'user',
    Individual: 'individual',
    Serviceprovider: 'serviceprovider',
    Beneficiary: 'beneficiary'
} as const;
export type GetNotificationDetailsEntitytypeEnum = typeof GetNotificationDetailsEntitytypeEnum[keyof typeof GetNotificationDetailsEntitytypeEnum];
/**
 * @export
 */
export const UpdateNotificationEntitytypeEnum = {
    Account: 'account',
    User: 'user',
    Individual: 'individual',
    Serviceprovider: 'serviceprovider',
    Beneficiary: 'beneficiary'
} as const;
export type UpdateNotificationEntitytypeEnum = typeof UpdateNotificationEntitytypeEnum[keyof typeof UpdateNotificationEntitytypeEnum];


