/* tslint:disable */
/* eslint-disable */
/**
 * SecuredContentLimited API
 * API for managing SecuredContentLimited entities
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface SecuredContentLimited
 */
export interface SecuredContentLimited {
    /**
     * 
     * @type {string}
     * @memberof SecuredContentLimited
     */
    'id': string;
    /**
     * 
     * @type {{ [key: string]: Tag; }}
     * @memberof SecuredContentLimited
     */
    'tags'?: { [key: string]: Tag; };
    /**
     * 
     * @type {string}
     * @memberof SecuredContentLimited
     */
    'updated'?: string;
    /**
     * 
     * @type {string}
     * @memberof SecuredContentLimited
     */
    'created'?: string;
}
/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * The name of the tag
     * @type {string}
     * @memberof Tag
     */
    'Name'?: string;
    /**
     * 
     * @type {TagValue}
     * @memberof Tag
     */
    'Value'?: TagValue;
    /**
     * Whether the tag is private
     * @type {boolean}
     * @memberof Tag
     */
    'Private'?: boolean;
    /**
     * Whether the tag is required
     * @type {boolean}
     * @memberof Tag
     */
    'Required'?: boolean;
    /**
     * Whether the tag is editable
     * @type {boolean}
     * @memberof Tag
     */
    'Editable'?: boolean;
}
/**
 * @type TagValue
 * The value of the tag
 * @export
 */
export type TagValue = boolean | number | string;


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new SecuredContentLimited entity
         * @param {SecuredContentLimited} securedContentLimited 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSecuredContent: async (securedContentLimited: SecuredContentLimited, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'securedContentLimited' is not null or undefined
            assertParamExists('createSecuredContent', 'securedContentLimited', securedContentLimited)
            const localVarPath = `/securedcontent`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(securedContentLimited, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a SecuredContentLimited entity by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSecuredContent: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteSecuredContent', 'id', id)
            const localVarPath = `/securedcontent/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all SecuredContentLimited entities for the logged-in user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSecuredContents: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/securedcontent`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a SecuredContentLimited entity by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSecuredContentDetails: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSecuredContentDetails', 'id', id)
            const localVarPath = `/securedcontent/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an existing SecuredContentLimited entity by ID
         * @param {string} id 
         * @param {SecuredContentLimited} securedContentLimited 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSecuredContent: async (id: string, securedContentLimited: SecuredContentLimited, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateSecuredContent', 'id', id)
            // verify required parameter 'securedContentLimited' is not null or undefined
            assertParamExists('updateSecuredContent', 'securedContentLimited', securedContentLimited)
            const localVarPath = `/securedcontent/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(securedContentLimited, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new SecuredContentLimited entity
         * @param {SecuredContentLimited} securedContentLimited 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSecuredContent(securedContentLimited: SecuredContentLimited, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SecuredContentLimited>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSecuredContent(securedContentLimited, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createSecuredContent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a SecuredContentLimited entity by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSecuredContent(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSecuredContent(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteSecuredContent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all SecuredContentLimited entities for the logged-in user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllSecuredContents(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SecuredContentLimited>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllSecuredContents(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAllSecuredContents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a SecuredContentLimited entity by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSecuredContentDetails(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SecuredContentLimited>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSecuredContentDetails(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getSecuredContentDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an existing SecuredContentLimited entity by ID
         * @param {string} id 
         * @param {SecuredContentLimited} securedContentLimited 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSecuredContent(id: string, securedContentLimited: SecuredContentLimited, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SecuredContentLimited>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSecuredContent(id, securedContentLimited, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateSecuredContent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new SecuredContentLimited entity
         * @param {SecuredContentLimited} securedContentLimited 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSecuredContent(securedContentLimited: SecuredContentLimited, options?: any): AxiosPromise<SecuredContentLimited> {
            return localVarFp.createSecuredContent(securedContentLimited, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a SecuredContentLimited entity by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSecuredContent(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteSecuredContent(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all SecuredContentLimited entities for the logged-in user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllSecuredContents(options?: any): AxiosPromise<Array<SecuredContentLimited>> {
            return localVarFp.getAllSecuredContents(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a SecuredContentLimited entity by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSecuredContentDetails(id: string, options?: any): AxiosPromise<SecuredContentLimited> {
            return localVarFp.getSecuredContentDetails(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an existing SecuredContentLimited entity by ID
         * @param {string} id 
         * @param {SecuredContentLimited} securedContentLimited 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSecuredContent(id: string, securedContentLimited: SecuredContentLimited, options?: any): AxiosPromise<SecuredContentLimited> {
            return localVarFp.updateSecuredContent(id, securedContentLimited, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Create a new SecuredContentLimited entity
     * @param {SecuredContentLimited} securedContentLimited 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createSecuredContent(securedContentLimited: SecuredContentLimited, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createSecuredContent(securedContentLimited, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a SecuredContentLimited entity by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteSecuredContent(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteSecuredContent(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all SecuredContentLimited entities for the logged-in user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAllSecuredContents(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAllSecuredContents(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a SecuredContentLimited entity by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getSecuredContentDetails(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getSecuredContentDetails(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an existing SecuredContentLimited entity by ID
     * @param {string} id 
     * @param {SecuredContentLimited} securedContentLimited 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateSecuredContent(id: string, securedContentLimited: SecuredContentLimited, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateSecuredContent(id, securedContentLimited, options).then((request) => request(this.axios, this.basePath));
    }
}



