/* tslint:disable */
/* eslint-disable */
/**
 * ServiceProviderLimited API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * @type GenericServiceProvider
 * @export
 */
export type GenericServiceProvider = PrivateServiceProvider | ServiceProviderLimited;

/**
 * 
 * @export
 * @interface PrivateServiceProvider
 */
export interface PrivateServiceProvider {
    /**
     * The unique identifier for the entity
     * @type {string}
     * @memberof PrivateServiceProvider
     */
    'id'?: string;
    /**
     * The unique identifier for the individual
     * @type {string}
     * @memberof PrivateServiceProvider
     */
    'individualid'?: string;
    /**
     * 
     * @type {{ [key: string]: Tag; }}
     * @memberof PrivateServiceProvider
     */
    'tags'?: { [key: string]: Tag; };
}
/**
 * 
 * @export
 * @interface ServiceProviderLimited
 */
export interface ServiceProviderLimited {
    /**
     * The unique identifier for the entity
     * @type {string}
     * @memberof ServiceProviderLimited
     */
    'id'?: string;
    /**
     * 
     * @type {{ [key: string]: Tag; }}
     * @memberof ServiceProviderLimited
     */
    'tags'?: { [key: string]: Tag; };
}
/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * The name of the tag
     * @type {string}
     * @memberof Tag
     */
    'Name'?: string;
    /**
     * 
     * @type {TagValue}
     * @memberof Tag
     */
    'Value'?: TagValue;
    /**
     * Whether the tag is private
     * @type {boolean}
     * @memberof Tag
     */
    'Private'?: boolean;
    /**
     * Whether the tag is required
     * @type {boolean}
     * @memberof Tag
     */
    'Required'?: boolean;
    /**
     * Whether the tag is editable
     * @type {boolean}
     * @memberof Tag
     */
    'Editable'?: boolean;
}
/**
 * @type TagValue
 * The value of the tag
 * @export
 */
export type TagValue = boolean | number | string;


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete specific private entity
         * @param {string} id The ID of the entity to delete
         * @param {boolean} [_private] true if private; default is false
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePrivateServiceProvider: async (id: string, _private?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePrivateServiceProvider', 'id', id)
            const localVarPath = `/serviceproviders/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (_private !== undefined) {
                localVarQueryParameter['private'] = _private;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List entities
         * @param {string} [searchText] The text to search for in Tag.Name or Tag.Value. If not provided, all Service Providers will be returned. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllServiceProviders: async (searchText?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/serviceproviders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (searchText !== undefined) {
                localVarQueryParameter['searchText'] = searchText;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get specific entity
         * @param {string} id The ID of the entity to retrieve
         * @param {boolean} [_private] true if private; default is false
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getServiceProviderDetails: async (id: string, _private?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getServiceProviderDetails', 'id', id)
            const localVarPath = `/serviceproviders/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (_private !== undefined) {
                localVarQueryParameter['private'] = _private;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update specific entity
         * @param {string} id The ID of the entity to update
         * @param {GenericServiceProvider} genericServiceProvider 
         * @param {boolean} [_private] true if private; default is false
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateServiceProvider: async (id: string, genericServiceProvider: GenericServiceProvider, _private?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateServiceProvider', 'id', id)
            // verify required parameter 'genericServiceProvider' is not null or undefined
            assertParamExists('updateServiceProvider', 'genericServiceProvider', genericServiceProvider)
            const localVarPath = `/serviceproviders/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (_private !== undefined) {
                localVarQueryParameter['private'] = _private;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(genericServiceProvider, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Delete specific private entity
         * @param {string} id The ID of the entity to delete
         * @param {boolean} [_private] true if private; default is false
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePrivateServiceProvider(id: string, _private?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePrivateServiceProvider(id, _private, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deletePrivateServiceProvider']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List entities
         * @param {string} [searchText] The text to search for in Tag.Name or Tag.Value. If not provided, all Service Providers will be returned. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllServiceProviders(searchText?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ServiceProviderLimited>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllServiceProviders(searchText, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAllServiceProviders']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get specific entity
         * @param {string} id The ID of the entity to retrieve
         * @param {boolean} [_private] true if private; default is false
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getServiceProviderDetails(id: string, _private?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericServiceProvider>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getServiceProviderDetails(id, _private, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getServiceProviderDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update specific entity
         * @param {string} id The ID of the entity to update
         * @param {GenericServiceProvider} genericServiceProvider 
         * @param {boolean} [_private] true if private; default is false
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateServiceProvider(id: string, genericServiceProvider: GenericServiceProvider, _private?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericServiceProvider>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateServiceProvider(id, genericServiceProvider, _private, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateServiceProvider']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Delete specific private entity
         * @param {string} id The ID of the entity to delete
         * @param {boolean} [_private] true if private; default is false
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePrivateServiceProvider(id: string, _private?: boolean, options?: any): AxiosPromise<void> {
            return localVarFp.deletePrivateServiceProvider(id, _private, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List entities
         * @param {string} [searchText] The text to search for in Tag.Name or Tag.Value. If not provided, all Service Providers will be returned. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllServiceProviders(searchText?: string, options?: any): AxiosPromise<Array<ServiceProviderLimited>> {
            return localVarFp.getAllServiceProviders(searchText, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get specific entity
         * @param {string} id The ID of the entity to retrieve
         * @param {boolean} [_private] true if private; default is false
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getServiceProviderDetails(id: string, _private?: boolean, options?: any): AxiosPromise<GenericServiceProvider> {
            return localVarFp.getServiceProviderDetails(id, _private, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update specific entity
         * @param {string} id The ID of the entity to update
         * @param {GenericServiceProvider} genericServiceProvider 
         * @param {boolean} [_private] true if private; default is false
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateServiceProvider(id: string, genericServiceProvider: GenericServiceProvider, _private?: boolean, options?: any): AxiosPromise<GenericServiceProvider> {
            return localVarFp.updateServiceProvider(id, genericServiceProvider, _private, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Delete specific private entity
     * @param {string} id The ID of the entity to delete
     * @param {boolean} [_private] true if private; default is false
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deletePrivateServiceProvider(id: string, _private?: boolean, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deletePrivateServiceProvider(id, _private, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List entities
     * @param {string} [searchText] The text to search for in Tag.Name or Tag.Value. If not provided, all Service Providers will be returned. 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAllServiceProviders(searchText?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAllServiceProviders(searchText, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get specific entity
     * @param {string} id The ID of the entity to retrieve
     * @param {boolean} [_private] true if private; default is false
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getServiceProviderDetails(id: string, _private?: boolean, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getServiceProviderDetails(id, _private, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update specific entity
     * @param {string} id The ID of the entity to update
     * @param {GenericServiceProvider} genericServiceProvider 
     * @param {boolean} [_private] true if private; default is false
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateServiceProvider(id: string, genericServiceProvider: GenericServiceProvider, _private?: boolean, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateServiceProvider(id, genericServiceProvider, _private, options).then((request) => request(this.axios, this.basePath));
    }
}



