/* tslint:disable */
/* eslint-disable */
/**
 * Account API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    'ID'?: string;
    /**
     * 
     * @type {{ [key: string]: Tag; }}
     * @memberof Account
     */
    'tags'?: { [key: string]: Tag; };
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof Account
     */
    'ServiceProviders'?: { [key: string]: boolean; };
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof Account
     */
    'Beneficiaries'?: { [key: string]: boolean; };
    /**
     * Timestamp of when the account was created.
     * @type {number}
     * @memberof Account
     */
    'created'?: number;
    /**
     * Timestamp of when the account was last updated.
     * @type {number}
     * @memberof Account
     */
    'updated'?: number;
}
/**
 * 
 * @export
 * @interface AccountInput
 */
export interface AccountInput {
    /**
     * 
     * @type {string}
     * @memberof AccountInput
     */
    'ID'?: string;
    /**
     * 
     * @type {{ [key: string]: Tag; }}
     * @memberof AccountInput
     */
    'tags'?: { [key: string]: Tag; };
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof AccountInput
     */
    'ServiceProviders'?: { [key: string]: boolean; };
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof AccountInput
     */
    'Beneficiaries'?: { [key: string]: boolean; };
}
/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * The name of the tag
     * @type {string}
     * @memberof Tag
     */
    'Name'?: string;
    /**
     * 
     * @type {TagValue}
     * @memberof Tag
     */
    'Value'?: TagValue;
    /**
     * Whether the tag is private
     * @type {boolean}
     * @memberof Tag
     */
    'Private'?: boolean;
    /**
     * Whether the tag is required
     * @type {boolean}
     * @memberof Tag
     */
    'Required'?: boolean;
    /**
     * Whether the tag is editable
     * @type {boolean}
     * @memberof Tag
     */
    'Editable'?: boolean;
}
/**
 * @type TagValue
 * The value of the tag
 * @export
 */
export type TagValue = boolean | number | object | string;


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new account
         * @param {AccountInput} accountInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewAccount: async (accountInput: AccountInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountInput' is not null or undefined
            assertParamExists('createNewAccount', 'accountInput', accountInput)
            const localVarPath = `/accounts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(accountInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a specific account by ID
         * @param {string} accountID The ID of the account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAccount: async (accountID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountID' is not null or undefined
            assertParamExists('deleteAccount', 'accountID', accountID)
            const localVarPath = `/accounts/{accountID}`
                .replace(`{${"accountID"}}`, encodeURIComponent(String(accountID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve a specific account by ID
         * @param {string} accountID The ID of the account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccountDetails: async (accountID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountID' is not null or undefined
            assertParamExists('getAccountDetails', 'accountID', accountID)
            const localVarPath = `/accounts/{accountID}`
                .replace(`{${"accountID"}}`, encodeURIComponent(String(accountID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve all account IDs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAccountIds: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/accounts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a specific account by ID
         * @param {string} accountID The ID of the account
         * @param {AccountInput} accountInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAccount: async (accountID: string, accountInput: AccountInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountID' is not null or undefined
            assertParamExists('updateAccount', 'accountID', accountID)
            // verify required parameter 'accountInput' is not null or undefined
            assertParamExists('updateAccount', 'accountInput', accountInput)
            const localVarPath = `/accounts/{accountID}`
                .replace(`{${"accountID"}}`, encodeURIComponent(String(accountID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(accountInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new account
         * @param {AccountInput} accountInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNewAccount(accountInput: AccountInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Account>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createNewAccount(accountInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createNewAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a specific account by ID
         * @param {string} accountID The ID of the account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAccount(accountID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAccount(accountID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieve a specific account by ID
         * @param {string} accountID The ID of the account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAccountDetails(accountID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Account>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAccountDetails(accountID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAccountDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieve all account IDs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllAccountIds(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllAccountIds(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAllAccountIds']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a specific account by ID
         * @param {string} accountID The ID of the account
         * @param {AccountInput} accountInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAccount(accountID: string, accountInput: AccountInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Account>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAccount(accountID, accountInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new account
         * @param {AccountInput} accountInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewAccount(accountInput: AccountInput, options?: any): AxiosPromise<Account> {
            return localVarFp.createNewAccount(accountInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a specific account by ID
         * @param {string} accountID The ID of the account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAccount(accountID: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteAccount(accountID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve a specific account by ID
         * @param {string} accountID The ID of the account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccountDetails(accountID: string, options?: any): AxiosPromise<Account> {
            return localVarFp.getAccountDetails(accountID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve all account IDs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAccountIds(options?: any): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.getAllAccountIds(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a specific account by ID
         * @param {string} accountID The ID of the account
         * @param {AccountInput} accountInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAccount(accountID: string, accountInput: AccountInput, options?: any): AxiosPromise<Account> {
            return localVarFp.updateAccount(accountID, accountInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Create a new account
     * @param {AccountInput} accountInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createNewAccount(accountInput: AccountInput, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createNewAccount(accountInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a specific account by ID
     * @param {string} accountID The ID of the account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteAccount(accountID: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteAccount(accountID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve a specific account by ID
     * @param {string} accountID The ID of the account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAccountDetails(accountID: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAccountDetails(accountID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve all account IDs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAllAccountIds(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAllAccountIds(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a specific account by ID
     * @param {string} accountID The ID of the account
     * @param {AccountInput} accountInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateAccount(accountID: string, accountInput: AccountInput, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateAccount(accountID, accountInput, options).then((request) => request(this.axios, this.basePath));
    }
}



