/* tslint:disable */
/* eslint-disable */
/**
 * Requests Management API
 * API for creating requests.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * @type CombinedResponse
 * @export
 */
export type CombinedResponse = any;

/**
 * 
 * @export
 * @interface Request
 */
export interface Request {
    /**
     * The ID (UUID format). d3f399b4-73f1-4cf1-98a3-2c2d35ab2c55
     * @type {string}
     * @memberof Request
     */
    'id'?: string;
    /**
     * The ID (UUID format). d3f399b4-73f1-4cf1-98a3-2c2d35ab2c55
     * @type {string}
     * @memberof Request
     */
    'fromIndividualID'?: string;
    /**
     * The email of requestee john.doe@domain.com
     * @type {string}
     * @memberof Request
     */
    'fromIndividualEmail'?: string;
    /**
     * The ID (UUID format). d3f399b4-73f1-4cf1-98a3-2c2d35ab2c55
     * @type {string}
     * @memberof Request
     */
    'toIndividualID'?: string;
    /**
     * The email of requestee john.doe@domain.com
     * @type {string}
     * @memberof Request
     */
    'toIndividualEmail'?: string;
    /**
     * The ID (UUID format). d3f399b4-73f1-4cf1-98a3-2c2d35ab2c55
     * @type {string}
     * @memberof Request
     */
    'fromServiceProviderID'?: string;
    /**
     * The ID (UUID format). d3f399b4-73f1-4cf1-98a3-2c2d35ab2c55
     * @type {string}
     * @memberof Request
     */
    'toServiceProviderID'?: string;
    /**
     * The ID (UUID format). d3f399b4-73f1-4cf1-98a3-2c2d35ab2c55
     * @type {string}
     * @memberof Request
     */
    'fromBeneficiaryID'?: string;
    /**
     * The ID (UUID format). d3f399b4-73f1-4cf1-98a3-2c2d35ab2c55
     * @type {string}
     * @memberof Request
     */
    'toBeneficiaryID'?: string;
    /**
     * 
     * @type {RequestType}
     * @memberof Request
     */
    'requestType'?: RequestType;
    /**
     * 
     * @type {RequestStatus}
     * @memberof Request
     */
    'status'?: RequestStatus;
    /**
     * 
     * @type {{ [key: string]: Tag; }}
     * @memberof Request
     */
    'tags'?: { [key: string]: Tag; };
    /**
     * The ID (UUID format). d3f399b4-73f1-4cf1-98a3-2c2d35ab2c55
     * @type {string}
     * @memberof Request
     */
    'addressID'?: string;
    /**
     * The creation time of the request as a unix epoch.
     * @type {number}
     * @memberof Request
     */
    'createdAt'?: number;
    /**
     * The modification time of the request as a unix epoch.
     * @type {number}
     * @memberof Request
     */
    'modifiedAt'?: number;
}


/**
 * 
 * @export
 * @interface RequestInput
 */
export interface RequestInput {
    /**
     * 
     * @type {RequestType}
     * @memberof RequestInput
     */
    'requestType': RequestType;
    /**
     * 
     * @type {RequestStatus}
     * @memberof RequestInput
     */
    'status': RequestStatus;
    /**
     * 
     * @type {{ [key: string]: Tag; }}
     * @memberof RequestInput
     */
    'tags': { [key: string]: Tag; };
    /**
     * The ID (UUID format). d3f399b4-73f1-4cf1-98a3-2c2d35ab2c55
     * @type {string}
     * @memberof RequestInput
     */
    'addressID': string;
}


/**
 * Status of request:   * `NEW` - Request has been just created 
 * @export
 * @enum {string}
 */

export const RequestStatus = {
    New: 'NEW'
} as const;

export type RequestStatus = typeof RequestStatus[keyof typeof RequestStatus];


/**
 * Type of request:   * `SHARE_ADDRESS` - Requestor requesting requestee to share an address with requestor 
 * @export
 * @enum {string}
 */

export const RequestType = {
    ShareAddress: 'SHARE_ADDRESS'
} as const;

export type RequestType = typeof RequestType[keyof typeof RequestType];


/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * The name of the tag
     * @type {string}
     * @memberof Tag
     */
    'Name'?: string;
    /**
     * 
     * @type {TagValue}
     * @memberof Tag
     */
    'Value'?: TagValue;
    /**
     * Whether the tag is private
     * @type {boolean}
     * @memberof Tag
     */
    'Private'?: boolean;
    /**
     * Whether the tag is required
     * @type {boolean}
     * @memberof Tag
     */
    'Required'?: boolean;
    /**
     * Whether the tag is editable
     * @type {boolean}
     * @memberof Tag
     */
    'Editable'?: boolean;
}
/**
 * @type TagValue
 * The value of the tag
 * @export
 */
export type TagValue = boolean | number | string;


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a request from one individual to another individual
         * @summary Create Request
         * @param {string} idFrom The ID of the requestor entity
         * @param {string} emailTo The email of the requestee entity
         * @param {RequestInput} requestInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRequestToEmail: async (idFrom: string, emailTo: string, requestInput: RequestInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idFrom' is not null or undefined
            assertParamExists('createRequestToEmail', 'idFrom', idFrom)
            // verify required parameter 'emailTo' is not null or undefined
            assertParamExists('createRequestToEmail', 'emailTo', emailTo)
            // verify required parameter 'requestInput' is not null or undefined
            assertParamExists('createRequestToEmail', 'requestInput', requestInput)
            const localVarPath = `/requests/individual/{idFrom}/individual/{emailTo}`
                .replace(`{${"idFrom"}}`, encodeURIComponent(String(idFrom)))
                .replace(`{${"emailTo"}}`, encodeURIComponent(String(emailTo)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes the specific request
         * @summary Deletes the specific request
         * @param {string} id The ID of the request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRequest: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteRequest', 'id', id)
            const localVarPath = `/requests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the specific request
         * @summary Returns the specific request
         * @param {string} id The ID of the request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequestDetails: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getRequestDetails', 'id', id)
            const localVarPath = `/requests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all requests where the individual is the requestor
         * @summary Returns all requests where the individual is the requestor
         * @param {string} id The ID of the requestor entity
         * @param {boolean} [_short] If given as true, will return a Request object as a response but with short list of fields
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequestsFromIndividual: async (id: string, _short?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getRequestsFromIndividual', 'id', id)
            const localVarPath = `/requests/individual/from/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (_short !== undefined) {
                localVarQueryParameter['short'] = _short;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all requests where the individual is the requestee
         * @summary Returns all requests where the individual is the requestee
         * @param {string} id The ID of the requestee entity
         * @param {boolean} [_short] If given as true, will return a Request object as a response but with short list of fields
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequestsToIndividual: async (id: string, _short?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getRequestsToIndividual', 'id', id)
            const localVarPath = `/requests/individual/to/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (_short !== undefined) {
                localVarQueryParameter['short'] = _short;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the updated request
         * @summary Updates the specific request
         * @param {string} id The ID of the request
         * @param {RequestInput} requestInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRequest: async (id: string, requestInput: RequestInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateRequest', 'id', id)
            // verify required parameter 'requestInput' is not null or undefined
            assertParamExists('updateRequest', 'requestInput', requestInput)
            const localVarPath = `/requests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a request from one individual to another individual
         * @summary Create Request
         * @param {string} idFrom The ID of the requestor entity
         * @param {string} emailTo The email of the requestee entity
         * @param {RequestInput} requestInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRequestToEmail(idFrom: string, emailTo: string, requestInput: RequestInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Request>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRequestToEmail(idFrom, emailTo, requestInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createRequestToEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes the specific request
         * @summary Deletes the specific request
         * @param {string} id The ID of the request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRequest(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRequest(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the specific request
         * @summary Returns the specific request
         * @param {string} id The ID of the request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRequestDetails(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Request>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRequestDetails(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getRequestDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns all requests where the individual is the requestor
         * @summary Returns all requests where the individual is the requestor
         * @param {string} id The ID of the requestor entity
         * @param {boolean} [_short] If given as true, will return a Request object as a response but with short list of fields
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRequestsFromIndividual(id: string, _short?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CombinedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRequestsFromIndividual(id, _short, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getRequestsFromIndividual']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns all requests where the individual is the requestee
         * @summary Returns all requests where the individual is the requestee
         * @param {string} id The ID of the requestee entity
         * @param {boolean} [_short] If given as true, will return a Request object as a response but with short list of fields
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRequestsToIndividual(id: string, _short?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CombinedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRequestsToIndividual(id, _short, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getRequestsToIndividual']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the updated request
         * @summary Updates the specific request
         * @param {string} id The ID of the request
         * @param {RequestInput} requestInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateRequest(id: string, requestInput: RequestInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Request>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateRequest(id, requestInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Creates a request from one individual to another individual
         * @summary Create Request
         * @param {string} idFrom The ID of the requestor entity
         * @param {string} emailTo The email of the requestee entity
         * @param {RequestInput} requestInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRequestToEmail(idFrom: string, emailTo: string, requestInput: RequestInput, options?: any): AxiosPromise<Request> {
            return localVarFp.createRequestToEmail(idFrom, emailTo, requestInput, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes the specific request
         * @summary Deletes the specific request
         * @param {string} id The ID of the request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRequest(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteRequest(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the specific request
         * @summary Returns the specific request
         * @param {string} id The ID of the request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequestDetails(id: string, options?: any): AxiosPromise<Request> {
            return localVarFp.getRequestDetails(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns all requests where the individual is the requestor
         * @summary Returns all requests where the individual is the requestor
         * @param {string} id The ID of the requestor entity
         * @param {boolean} [_short] If given as true, will return a Request object as a response but with short list of fields
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequestsFromIndividual(id: string, _short?: boolean, options?: any): AxiosPromise<CombinedResponse> {
            return localVarFp.getRequestsFromIndividual(id, _short, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns all requests where the individual is the requestee
         * @summary Returns all requests where the individual is the requestee
         * @param {string} id The ID of the requestee entity
         * @param {boolean} [_short] If given as true, will return a Request object as a response but with short list of fields
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequestsToIndividual(id: string, _short?: boolean, options?: any): AxiosPromise<CombinedResponse> {
            return localVarFp.getRequestsToIndividual(id, _short, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the updated request
         * @summary Updates the specific request
         * @param {string} id The ID of the request
         * @param {RequestInput} requestInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRequest(id: string, requestInput: RequestInput, options?: any): AxiosPromise<Request> {
            return localVarFp.updateRequest(id, requestInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Creates a request from one individual to another individual
     * @summary Create Request
     * @param {string} idFrom The ID of the requestor entity
     * @param {string} emailTo The email of the requestee entity
     * @param {RequestInput} requestInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createRequestToEmail(idFrom: string, emailTo: string, requestInput: RequestInput, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createRequestToEmail(idFrom, emailTo, requestInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes the specific request
     * @summary Deletes the specific request
     * @param {string} id The ID of the request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteRequest(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteRequest(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the specific request
     * @summary Returns the specific request
     * @param {string} id The ID of the request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getRequestDetails(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getRequestDetails(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns all requests where the individual is the requestor
     * @summary Returns all requests where the individual is the requestor
     * @param {string} id The ID of the requestor entity
     * @param {boolean} [_short] If given as true, will return a Request object as a response but with short list of fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getRequestsFromIndividual(id: string, _short?: boolean, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getRequestsFromIndividual(id, _short, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns all requests where the individual is the requestee
     * @summary Returns all requests where the individual is the requestee
     * @param {string} id The ID of the requestee entity
     * @param {boolean} [_short] If given as true, will return a Request object as a response but with short list of fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getRequestsToIndividual(id: string, _short?: boolean, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getRequestsToIndividual(id, _short, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the updated request
     * @summary Updates the specific request
     * @param {string} id The ID of the request
     * @param {RequestInput} requestInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateRequest(id: string, requestInput: RequestInput, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateRequest(id, requestInput, options).then((request) => request(this.axios, this.basePath));
    }
}



