/* tslint:disable */
/* eslint-disable */
/**
 * ServiceProviderLimited API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface BeneficiaryLimited
 */
export interface BeneficiaryLimited {
    /**
     * The unique identifier for the entity
     * @type {string}
     * @memberof BeneficiaryLimited
     */
    'id'?: string;
    /**
     * 
     * @type {{ [key: string]: Tag; }}
     * @memberof BeneficiaryLimited
     */
    'tags'?: { [key: string]: Tag; };
}
/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * The name of the tag
     * @type {string}
     * @memberof Tag
     */
    'Name'?: string;
    /**
     * 
     * @type {TagValue}
     * @memberof Tag
     */
    'Value'?: TagValue;
    /**
     * Whether the tag is private
     * @type {boolean}
     * @memberof Tag
     */
    'Private'?: boolean;
    /**
     * Whether the tag is required
     * @type {boolean}
     * @memberof Tag
     */
    'Required'?: boolean;
    /**
     * Whether the tag is editable
     * @type {boolean}
     * @memberof Tag
     */
    'Editable'?: boolean;
}
/**
 * @type TagValue
 * The value of the tag
 * @export
 */
export type TagValue = boolean | number | object | string;


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List entities
         * @param {string} [searchText] The text to search for in Tag.Name or Tag.Value. If not provided, all beneficiaries will be returned. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBeneficiaries: async (searchText?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/beneficiaries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (searchText !== undefined) {
                localVarQueryParameter['searchText'] = searchText;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get specific entity
         * @param {string} id The ID of the entity to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBeneficiaryDetails: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getBeneficiaryDetails', 'id', id)
            const localVarPath = `/beneficiaries/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update specific entity
         * @param {string} id The ID of the entity to update
         * @param {BeneficiaryLimited} beneficiaryLimited 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBeneficiary: async (id: string, beneficiaryLimited: BeneficiaryLimited, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateBeneficiary', 'id', id)
            // verify required parameter 'beneficiaryLimited' is not null or undefined
            assertParamExists('updateBeneficiary', 'beneficiaryLimited', beneficiaryLimited)
            const localVarPath = `/beneficiaries/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(beneficiaryLimited, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List entities
         * @param {string} [searchText] The text to search for in Tag.Name or Tag.Value. If not provided, all beneficiaries will be returned. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBeneficiaries(searchText?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BeneficiaryLimited>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBeneficiaries(searchText, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getBeneficiaries']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get specific entity
         * @param {string} id The ID of the entity to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBeneficiaryDetails(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BeneficiaryLimited>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBeneficiaryDetails(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getBeneficiaryDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update specific entity
         * @param {string} id The ID of the entity to update
         * @param {BeneficiaryLimited} beneficiaryLimited 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateBeneficiary(id: string, beneficiaryLimited: BeneficiaryLimited, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BeneficiaryLimited>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateBeneficiary(id, beneficiaryLimited, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateBeneficiary']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary List entities
         * @param {string} [searchText] The text to search for in Tag.Name or Tag.Value. If not provided, all beneficiaries will be returned. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBeneficiaries(searchText?: string, options?: any): AxiosPromise<Array<BeneficiaryLimited>> {
            return localVarFp.getBeneficiaries(searchText, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get specific entity
         * @param {string} id The ID of the entity to retrieve
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBeneficiaryDetails(id: string, options?: any): AxiosPromise<BeneficiaryLimited> {
            return localVarFp.getBeneficiaryDetails(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update specific entity
         * @param {string} id The ID of the entity to update
         * @param {BeneficiaryLimited} beneficiaryLimited 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBeneficiary(id: string, beneficiaryLimited: BeneficiaryLimited, options?: any): AxiosPromise<BeneficiaryLimited> {
            return localVarFp.updateBeneficiary(id, beneficiaryLimited, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary List entities
     * @param {string} [searchText] The text to search for in Tag.Name or Tag.Value. If not provided, all beneficiaries will be returned. 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getBeneficiaries(searchText?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getBeneficiaries(searchText, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get specific entity
     * @param {string} id The ID of the entity to retrieve
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getBeneficiaryDetails(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getBeneficiaryDetails(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update specific entity
     * @param {string} id The ID of the entity to update
     * @param {BeneficiaryLimited} beneficiaryLimited 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateBeneficiary(id: string, beneficiaryLimited: BeneficiaryLimited, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateBeneficiary(id, beneficiaryLimited, options).then((request) => request(this.axios, this.basePath));
    }
}



