/* tslint:disable */
/* eslint-disable */
/**
 * Your API Name
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Record
 */
export interface Record {
    /**
     * 
     * @type {string}
     * @memberof Record
     */
    'individualID'?: string;
    /**
     * 
     * @type {string}
     * @memberof Record
     */
    'addressID'?: string;
    /**
     * 
     * @type {string}
     * @memberof Record
     */
    'serviceProviderID'?: string;
    /**
     * 
     * @type {string}
     * @memberof Record
     */
    'beneficiaryID'?: string;
    /**
     * 
     * @type {string}
     * @memberof Record
     */
    'token'?: string;
    /**
     * 
     * @type {{ [key: string]: Tag; }}
     * @memberof Record
     */
    'tags'?: { [key: string]: Tag; };
    /**
     * 
     * @type {string}
     * @memberof Record
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof Record
     */
    'updated'?: string;
}
/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * The name of the tag
     * @type {string}
     * @memberof Tag
     */
    'Name'?: string;
    /**
     * 
     * @type {TagValue}
     * @memberof Tag
     */
    'Value'?: TagValue;
    /**
     * Whether the tag is private
     * @type {boolean}
     * @memberof Tag
     */
    'Private'?: boolean;
    /**
     * Whether the tag is required
     * @type {boolean}
     * @memberof Tag
     */
    'Required'?: boolean;
    /**
     * Whether the tag is editable
     * @type {boolean}
     * @memberof Tag
     */
    'Editable'?: boolean;
}
/**
 * @type TagValue
 * The value of the tag
 * @export
 */
export type TagValue = boolean | number | string;


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a record by address ID
         * @param {string} addressID UUID of the address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAddressRecords: async (addressID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addressID' is not null or undefined
            assertParamExists('getAddressRecords', 'addressID', addressID)
            const localVarPath = `/records/Address/{addressID}`
                .replace(`{${"addressID"}}`, encodeURIComponent(String(addressID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a record by beneficiary ID
         * @param {string} beneficiaryID UUID of the beneficiary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBeneficiaryRecords: async (beneficiaryID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'beneficiaryID' is not null or undefined
            assertParamExists('getBeneficiaryRecords', 'beneficiaryID', beneficiaryID)
            const localVarPath = `/records/Beneficiary/{beneficiaryID}`
                .replace(`{${"beneficiaryID"}}`, encodeURIComponent(String(beneficiaryID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get records by address and beneficiary IDs
         * @param {string} addressID UUID of the address
         * @param {string} beneficiaryID UUID of the beneficiary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBeneficiaryRecordsForAddress: async (addressID: string, beneficiaryID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addressID' is not null or undefined
            assertParamExists('getBeneficiaryRecordsForAddress', 'addressID', addressID)
            // verify required parameter 'beneficiaryID' is not null or undefined
            assertParamExists('getBeneficiaryRecordsForAddress', 'beneficiaryID', beneficiaryID)
            const localVarPath = `/records/AddressAndBeneficiary/{addressID}/{beneficiaryID}`
                .replace(`{${"addressID"}}`, encodeURIComponent(String(addressID)))
                .replace(`{${"beneficiaryID"}}`, encodeURIComponent(String(beneficiaryID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get records by individual ID
         * @param {string} individualID UUID of the individual
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIndividualRecords: async (individualID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'individualID' is not null or undefined
            assertParamExists('getIndividualRecords', 'individualID', individualID)
            const localVarPath = `/records/Individual/{individualID}`
                .replace(`{${"individualID"}}`, encodeURIComponent(String(individualID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a record by service provider ID
         * @param {string} serviceProviderID UUID of the service provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getServiceProviderRecords: async (serviceProviderID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'serviceProviderID' is not null or undefined
            assertParamExists('getServiceProviderRecords', 'serviceProviderID', serviceProviderID)
            const localVarPath = `/records/ServiceProvider/{serviceProviderID}`
                .replace(`{${"serviceProviderID"}}`, encodeURIComponent(String(serviceProviderID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a record by service provider ID
         * @param {string} addressID UUID of the address
         * @param {string} serviceProviderID UUID of the service provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getServiceProviderRecordsForAddress: async (addressID: string, serviceProviderID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addressID' is not null or undefined
            assertParamExists('getServiceProviderRecordsForAddress', 'addressID', addressID)
            // verify required parameter 'serviceProviderID' is not null or undefined
            assertParamExists('getServiceProviderRecordsForAddress', 'serviceProviderID', serviceProviderID)
            const localVarPath = `/records/AddressAndServiceProvider/{addressID}/{serviceProviderID}`
                .replace(`{${"addressID"}}`, encodeURIComponent(String(addressID)))
                .replace(`{${"serviceProviderID"}}`, encodeURIComponent(String(serviceProviderID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get a record by address ID
         * @param {string} addressID UUID of the address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAddressRecords(addressID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Record>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAddressRecords(addressID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAddressRecords']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a record by beneficiary ID
         * @param {string} beneficiaryID UUID of the beneficiary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBeneficiaryRecords(beneficiaryID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Record>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBeneficiaryRecords(beneficiaryID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getBeneficiaryRecords']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get records by address and beneficiary IDs
         * @param {string} addressID UUID of the address
         * @param {string} beneficiaryID UUID of the beneficiary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBeneficiaryRecordsForAddress(addressID: string, beneficiaryID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Record>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBeneficiaryRecordsForAddress(addressID, beneficiaryID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getBeneficiaryRecordsForAddress']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get records by individual ID
         * @param {string} individualID UUID of the individual
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIndividualRecords(individualID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Record>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getIndividualRecords(individualID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getIndividualRecords']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a record by service provider ID
         * @param {string} serviceProviderID UUID of the service provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getServiceProviderRecords(serviceProviderID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Record>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getServiceProviderRecords(serviceProviderID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getServiceProviderRecords']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a record by service provider ID
         * @param {string} addressID UUID of the address
         * @param {string} serviceProviderID UUID of the service provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getServiceProviderRecordsForAddress(addressID: string, serviceProviderID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Record>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getServiceProviderRecordsForAddress(addressID, serviceProviderID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getServiceProviderRecordsForAddress']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Get a record by address ID
         * @param {string} addressID UUID of the address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAddressRecords(addressID: string, options?: any): AxiosPromise<Array<Record>> {
            return localVarFp.getAddressRecords(addressID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a record by beneficiary ID
         * @param {string} beneficiaryID UUID of the beneficiary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBeneficiaryRecords(beneficiaryID: string, options?: any): AxiosPromise<Array<Record>> {
            return localVarFp.getBeneficiaryRecords(beneficiaryID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get records by address and beneficiary IDs
         * @param {string} addressID UUID of the address
         * @param {string} beneficiaryID UUID of the beneficiary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBeneficiaryRecordsForAddress(addressID: string, beneficiaryID: string, options?: any): AxiosPromise<Array<Record>> {
            return localVarFp.getBeneficiaryRecordsForAddress(addressID, beneficiaryID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get records by individual ID
         * @param {string} individualID UUID of the individual
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIndividualRecords(individualID: string, options?: any): AxiosPromise<Array<Record>> {
            return localVarFp.getIndividualRecords(individualID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a record by service provider ID
         * @param {string} serviceProviderID UUID of the service provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getServiceProviderRecords(serviceProviderID: string, options?: any): AxiosPromise<Array<Record>> {
            return localVarFp.getServiceProviderRecords(serviceProviderID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a record by service provider ID
         * @param {string} addressID UUID of the address
         * @param {string} serviceProviderID UUID of the service provider
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getServiceProviderRecordsForAddress(addressID: string, serviceProviderID: string, options?: any): AxiosPromise<Array<Record>> {
            return localVarFp.getServiceProviderRecordsForAddress(addressID, serviceProviderID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Get a record by address ID
     * @param {string} addressID UUID of the address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAddressRecords(addressID: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAddressRecords(addressID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a record by beneficiary ID
     * @param {string} beneficiaryID UUID of the beneficiary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getBeneficiaryRecords(beneficiaryID: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getBeneficiaryRecords(beneficiaryID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get records by address and beneficiary IDs
     * @param {string} addressID UUID of the address
     * @param {string} beneficiaryID UUID of the beneficiary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getBeneficiaryRecordsForAddress(addressID: string, beneficiaryID: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getBeneficiaryRecordsForAddress(addressID, beneficiaryID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get records by individual ID
     * @param {string} individualID UUID of the individual
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getIndividualRecords(individualID: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getIndividualRecords(individualID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a record by service provider ID
     * @param {string} serviceProviderID UUID of the service provider
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getServiceProviderRecords(serviceProviderID: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getServiceProviderRecords(serviceProviderID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a record by service provider ID
     * @param {string} addressID UUID of the address
     * @param {string} serviceProviderID UUID of the service provider
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getServiceProviderRecordsForAddress(addressID: string, serviceProviderID: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getServiceProviderRecordsForAddress(addressID, serviceProviderID, options).then((request) => request(this.axios, this.basePath));
    }
}



